### ISSUE TITLE
SSD model can not convert to trt

### ISSUE THREAD

**Issue by jinfagang** [onnx/models#185] opened 2019-07-18 08:55 UTC
When convert ssd model to trt, got this:

```
----------------------------------------------------------------
Input filename:   model.onnx
ONNX IR version:  0.0.4
Opset version:    10
Producer name:    pytorch
Producer version: 1.1
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).
Parsing model
WARNING: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Successfully casted down to INT32.
While parsing node number 122 [Gather -> "Gather_341"]:
ERROR:onnx-tensorrt/onnx2trt_utils.hpp:335 In function convert_axis:
[8] Assertion failed: axis >= 0 && axis < nbDims

```

Once I got this situation, what should I do? Even the nvOnnxParse can not parse the model does it?

**Comment by ebarsoum** [comment] 2019-07-19 06:13
Hi @jinfagang can you try to convert the model to an older version? Using https://github.com/onnx/onnx/blob/master/docs/VersionConverter.md

**Comment by jinfagang** [comment] 2019-07-19 06:32
@ebarsoum  Thanks for you reply!

I am confused here, those error messages indicates me my onnx2trt too new or the model is too new???

I build onnx2trt from onnx_tensorrt with tensorrt5.1, I thought it was the newest version.

BTW, why does the new onnx model can not convert to trt engine? Is that onnx too new or tensorrt too old? I can not quite got it......

**Comment by ebarsoum** [comment] 2019-07-19 16:35
model is too new, TRT doesn't support opset10 yet.

**Comment by prasanthpul** [comment] 2019-07-19 18:35
If you want to run the model now, you can use [ONNX Runtime](https://github.com/microsoft/onnxruntime) to run it on CPU/GPU. ONNX Runtime also integrates with TRT as an accelerator so when TRT supports it, you can start getting the benefit without changing your integration code.

**Comment by jinfagang** [comment] 2019-07-20 02:29
@prasanthpul  Thanks! Seems ONNX Runtime is an optimistic option, however, it says ONNX Runtime supports up to opset10, but from @ebarsoum  claim TensorRT  does not support opset yet. So here is my 2 question?

1. Does ONNX Runtime possibly run new SSD model ?
2. What opset does TensorRT support to and when will support as new as ONNX?

**Comment by prasanthpul** [comment] 2019-07-21 17:20
Right, ONNX Runtime supports through opset 10. SSD model has been verified to work with it.

**Comment by jinfagang** [comment] 2019-07-22 02:44
@prasanthpul  Thanks a lot!! But, since ONNX runtime has tensorrt backend, but tensorrt does not support opset10, it means ONNX runtime supports SSD **does not using tensorrt**?

Since I am mainly wanna tensorrt accelerations through ONNX Runtime so this is important.

**Comment by snnn** [comment] 2019-07-30 00:26
Hi @jinfagang 
It works if:
1.  You are using onnxruntime python API but the python package wasn't built with tensorrt. 
2.  Or, you are using onnxruntime C/C++/C# API, and not register tensorrt as a backend.

**Comment by jinfagang** [comment] 2019-07-30 02:07
@snnn  Can it call TensorRT once that layer supported by TensorRT?

**Comment by snnn** [comment] 2019-07-30 04:53
By design, yes, it will work.
OnnxRuntime is an open source project, open to public. Welcome to contribute your code and ideas to make it better!

**Comment by xonobo** [comment] 2019-08-28 10:53
> When convert ssd model to trt, got this:
> 
> ```
> ----------------------------------------------------------------
> Input filename:   model.onnx
> ONNX IR version:  0.0.4
> Opset version:    10
> Producer name:    pytorch
> Producer version: 1.1
> Domain:           
> Model version:    0
> Doc string:       
> ----------------------------------------------------------------
> WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).
> Parsing model
> WARNING: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> Successfully casted down to INT32.
> While parsing node number 122 [Gather -> "Gather_341"]:
> ERROR:onnx-tensorrt/onnx2trt_utils.hpp:335 In function convert_axis:
> [8] Assertion failed: axis >= 0 && axis < nbDims
> ```
> 
> Once I got this situation, what should I do? Even the nvOnnxParse can not parse the model does it?

May I ask how you export an SSD model to onnx with opset 10. I am looking for it #204.

**Comment by jlucier** [comment] 2020-04-21 16:22
This might be relevant for anyone struggling with this issue (or similar) and stumbling on this:
https://github.com/NVIDIA/TensorRT/issues/148#issuecomment-617257189

**Comment by jcwchen** [comment] 2022-03-04 01:39
I think TRT supports opset10 now. Close this issue.

**Closed by jcwchen** 2022-03-04 01:39 UTC
