### ISSUE TITLE
Error with emotion_ferplus loaded in Caffe2

### ISSUE THREAD

**Issue by louisabraham** [onnx/models#37] opened 2018-04-13 13:31 UTC
Hi,

I used

    convert-onnx-to-caffe2 model.onnx -o predict_net.pb --init-net-output init_net.pb

But when trying to run it on an input, I get :

```
  File "/Users/louisabraham/miniconda3/lib/python3.6/site-packages/caffe2/python/workspace.py", line 212, in RunNetOnce
    StringifyProto(net),
  File "/Users/louisabraham/miniconda3/lib/python3.6/site-packages/caffe2/python/workspace.py", line 192, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at conv_pool_op_base.h:617] in_size + *pad_head + *pad_tail >= dkernel. 1 vs 3 Error from operator: 
input: "ReLU2700_Output_0" input: "Parameter675" output: "Convolution2714_Output_0" name: "Convolution2714" type: "Conv" arg { name: "kernels" ints: 3 ints: 3 } arg { name: "strides" ints: 1 ints: 1 } arg { name: "auto_pad" s: "SAME_UPPER" } arg { name: "group" i: 1 } arg { name: "dilations" ints: 1 ints: 1 } device_option { device_type: 0 cuda_gpu_id: 0 }
```

I think my input shape is correct (else I get an error on the first layer `input: "Input2505"`).

**Comment by lupesko** [comment] 2018-04-27 05:49
I think "auto_pad" attribute is deprecated, which is the root cause of the error.

**Comment by ebarsoumMS** [comment] 2018-04-27 17:44
@lupesko yes it is marked as deprecated but still part of the spec. We will update the model once we update CNTK to move away from auto_pad.

**Comment by ramkrishna2910** [comment] 2023-11-07 19:47
Hi, 
Since there hasn't been any activity on this issue for a while, I'm going to close it to help keep the issue tracker clean. However, if this issue is still relevant and you would like to continue the discussion or work on it, please feel free to reopen it or leave a comment, and we can take another look.

Thank you for your contributions!

**Closed by ramkrishna2910** 2023-11-07 19:47 UTC
